### ISSUE TITLE
installing pdfminer.six

### ISSUE THREAD

**Issue by rsaavy** [Azure/DataScienceVM#15]
Hey,

I wanted to install a python package called pdfminer.six 
i tried pip install  the package into the data science vm. i ran into issues.
![image](https://user-images.githubusercontent.com/18731785/46305050-4a6cde00-c57e-11e8-9d76-dd3152d1467e.png)

**Comment by gopitk** [comment]
Since conda environments are global, only Admin users can install packages in these global environments. You can start a command prompt or Anaconda prompt as an "Administrator" and then run pip or conda to install packages.
