### ISSUE TITLE
Open RStudio Server port on Linux images

### ISSUE THREAD

**Issue by Hong-Revo** [Azure/DataScienceVM#18]
Hi,

I had a user [try to use RStudio Server](https://github.com/cloudyr/AzureVM/issues/1) after deploying a DSVM. They found that they had to manually open the port before they could connect. Would it be worthwhile to open this port automatically for the Linux-based images?

**Comment by paulshealy1** [comment]
Hi Hong,

Was this DSVM deployed with an ARM template? If so, ARM requires the user to open this port himself. If you deploy through the portal we have configured it to automatically open this port on your behalf.

**Comment by Hong-Revo** [comment]
Yes, this would have been with a template (it's my R package for deploying VMs via ARM). I'll look into adding this feature to my code. Thanks.
