### ISSUE TITLE
Can I have a Windows like Desktop view for Linux DSVM.

### ISSUE THREAD

**Issue by vsatyav007** [Azure/DataScienceVM#21]
Can I have a Windows like Desktop view for Linux DSVM. I have created a Windows DSVM which feels same as windows desktop,Is there something like this in Linux DSVM so that i can directly connect using rdp file.

ps:I'm using a Linux DSVM for fastai course.

**Comment by csotomon** [comment]
You can use X2GO.

[https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-ubuntu-intro#how-to-access-the-ubuntu-data-science-virtual-machine](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-ubuntu-intro#how-to-access-the-ubuntu-data-science-virtual-machine)

**Comment by vsatyav007** [comment]
Thanks
