### ISSUE TITLE
Default Network Security Group configuration insecure

### ISSUE THREAD

**Issue by alexmg** [Azure/DataScienceVM#22]
When deploying DSVM through the Azure Portal the NSG configuration allows inbound connections on port 22 for any source IP address. After deploying such a DSVM in this manner it was not long before Security Center detected a brute force attack on that Virtual Machine with an attacker attempting to gain access via SSH. It may be worth considering starting with a more secure configuration accompanied by documentation on how to configure an inbound rule.

**Comment by samuel100** [comment]
The key aim of DSVM is to be low friction for a data scientist to get started with ML in the cloud, therefore it should be easy to connect. To this end, the default is to have ssh enabled. There is documentation for "enterprise patterns":

https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-enterprise-overview 

That articulates how to lock down ports, etc.

**Comment by alexmg** [comment]
I received an email notification with a comment that has since been deleted. I assume you no longer want that response to be public and will not repost it here.

I am a little surprised that Microsoft is placing convenience over security, but the decision to put machines onto the internet with the standard SSH port open for all source IP addresses is yours to make.

Instances of SQL Server require users to add firewall rules and the process is not that arduous. I think someone capable of performing data science activities would not find such a step challenging.

Yes, there is the [Enterprise security and guidance](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-enterprise-overview), but "Secure by default" should not just be for the enterprise. I would guess that many of the users deploying DSVM are employees of an enterprise and are doing so to avoid IT policies in the first place.
