### ISSUE TITLE
update jupyterlab on image to 1.0

### ISSUE THREAD

**Issue by rbavery** [Azure/DataScienceVM#23]
The 1.0.1 version is now out on conda and pip and should be officialy publicized soon: https://github.com/jupyterlab/jupyterlab/milestone/2

**Comment by rbavery** [comment]
I'd really like to use jupyterlab with the data science vm isntead of the old jupyter notebooks, but I can't install it.

To reproduce, provision the dsvm and try to install in either the py35 or py36 environments

```
(py36) ryan@cropmask-dev:~$ conda install -c conda-forge jupyterlab=1.0.6
```

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(696): An error occurred while installing package 'conda-forge::jupyterlab-1.0.6-py36_0'.
Rolling back transaction: done

[Errno 13] Permission denied: '/data/anaconda/envs/py36/etc/jupyter/jupyter_notebook_config.d'
()

```

**Comment by paulshealy** [comment]
Try installing with sudo:

    sudo -i
    conda activate py36
    conda install -c conda-forge jupyterlab=1.0.6

**Comment by rbavery** [comment]
that works thanks!
