### ISSUE TITLE
R kernels not working

### ISSUE THREAD

**Issue by timlod** [Azure/DataScienceVM#24]
Hi,
In any newly created DSVM (or new ML Notebook VM which I think is based on the DSVM), the R kernels are not working in Jupyter.
I've tried with multiple, freshly deployed VMs. 
The kernel tries to start up and then dies.

**Comment by paulshealy** [comment]
Thanks for reaching out. I've tried the R kernel on both the Ubuntu and Windows 2016 DSVMs, and both work fine. Can you try a new VM and see if you still have issues?

**Comment by timlod** [comment]
Sorry for the late response, I'm just sorting out some leftover issues. I haven't been working with these for a long time, so I'm going to assume it's fixed and close this.
