### ISSUE TITLE
Ubuntu deployment fails with linking error

### ISSUE THREAD

**Issue by andreas-wilm** [Azure/DataScienceVM#25]
Hello,

the deployment of `Scripts/CreateDSVM/Ubuntu/dsvm-vmss-cluster.json` (as mentioned in the [official docs](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/dsvm-pools)) fails with

> ln: failed to create symbolic link '/home/\<USER\>/notebooks/remote': No such file or directory"

which is triggered in `Extensions/General/mountazurefiles.sh` because the `notebooks` directory doesn't exist at the stage where the script is run.

For debugging I tried the following:
- Disable the linking command:  deployment works and the `notebooks` directory does exist, with autopopulated notebooks
- Create the directory before linking: deployment works, but the directory is not autopopulated with notebooks

So it seems that some process is creating that directory *after* `mountazurefiles.sh` is run.

Anyway, option 2 is probably the cleanest and can be achieved by running

    test -d /home/$5/notebooks || mkdir -p /home/$5/notebooks

before the `ln` line in `mountazurefiles.sh`. The only disadvantage is that the notebooks directory is then empty / not autopopulated. So this requires a proper fix. The best would be to run the mount script, after whatever process created `~/notebooks`

Andreas

**Comment by RichJackson** [comment]
I have the same issue - Docs are wrong
