### ISSUE TITLE
Typo 'descsription' is spelled wrong in AzureML Template ... it should be description

### ISSUE THREAD

**Issue by JakeRadMSFT** [Azure/DataScienceVM#26]
'descsription' is spelled wrong in AzureML Template ... it should be description

https://github.com/Azure/DataScienceVM/blob/f24feb07a9aa1aaf5738c7ecfc10f80d513e4fab/Scripts/AzureML/CreateAzureMLWSWithDsvm.json#L104

**Comment by JakeRadMSFT** [comment]
Here too:

https://github.com/Azure/DataScienceVM/blob/f24feb07a9aa1aaf5738c7ecfc10f80d513e4fab/Scripts/AzureML/CreateAzureMLWSWithDsvm.json#L104

**Comment by paulshealy1** [comment]
Thanks for reporting this! I've fixed it in both places.
