### ISSUE TITLE
Publish a Windows Server 2019 Datacenter edition image to the Azure Marketplace

### ISSUE THREAD

**Issue by geglne** [Azure/DataScienceVM#27]
As an admin of an Azure subscription, I would like a DataScienceVM image created on the  Windows Server 2019 Datacenter edition platform to enable users to login using Azure Active Directory authentication.

Recently it was [announced](https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows) (and still in preview as of 10/28/2019) the ability to sign into a Windows virtual machine using Azure Active Directory. This is only available for Windows Server 2019 Datacenter edition and later. However, currently the only available image for a Windows machine in the Marketplace is a Windows 2016 edition. 

Please create a new DataScienceVM on the Windows Server 2019 Datacenter edition platform so we may take advantage of this new feature.

**Comment by paulshealy1** [comment]
We are currently working on a Windows Server 2019 DSVM image, and we aim to release it in January. I have added AAD login to our backlog as an item to support on this image.

**Comment by samuel100** [comment]
Windows Server 2019 DSVM image is now available.
