### ISSUE TITLE
Where is ArcGIS desktop?

### ISSUE THREAD

**Issue by harmonyliu** [Azure/DataScienceVM#30]
where is the ArcGIS desktop installed? I can not find it in the start menu (can't find it by search either). I installed the "Geo Artificial Intelligence Data Science Virtual Machine" hoping I can use both ArcGIS desktop and Anaconda. Can we only use ArcGIS through arcpy through python on "Geo Artificial Intelligence Data Science Virtual Machine" ?

**Comment by banikaku** [comment]
We have ArcGISPro installed in it as shown below, I just tested it on a fresh VM (https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-ads.geodsvm) and found it working.

Ideally when the Geo AI DSVM provision is successful (it might take around 20 to 30 minutes to complete), if you login you should be able to find ArcGIS Pro installed .


![image](https://user-images.githubusercontent.com/57768415/76135198-8ad55480-5fd9-11ea-8813-4c9f72bfcb85.png)

**Comment by harmonyliu** [comment]
Hi there,

It is odd. I tried twice (delete-reinstall) using
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-ads.geodsvm,
and ArcGIS is not in my Start menu. I will delete this resource and try
again. I wonder if  there are some special settings I need to pick when
creating the resource.
[image: Screen Shot 2020-03-06 at 7.41.45 PM.png]

**Comment by Samir-Sell** [comment]
Where did this image go? The link is now dead and I cannot find another DSVM image that has ArcGIS pro on it?

**Comment by samuel100** [comment]
The GeoDSVM has been removed from the marketplace. Please contact Esri (support ticket) for assistance on getting a VM in Azure with ArcGIS installed.
