### ISSUE TITLE
Connect from R Studio to DataBricks

### ISSUE THREAD

**Issue by RajarshiBhadra** [Azure/DataScienceVM#33]
I am currently using R Studio for a project and I am trying to connect to my databricks cluster via sparklyr.

For this I am following the process as described here: https://spark.rstudio.com/examples/databricks-cluster-remote/

However when I try to do databrick-connect test I get the following error

Incompatible Jackson version: 2.10.0 databricks connect

Is there any way to get a concrete way of connecting dsvm R environment to databricks?

**Comment by samuel100** [comment]
Please note that we do not support databricks-connect on DSVM and [is not included "out-of-the-box"](https://docs.microsoft.com/en-us/azure/machine-learning/data-science-virtual-machine/tools-included). The issue described seems to be a databricks-connect issue and therefore it is worth starting a thread on [Azure Databricks Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-databricks.html).

It seems like the wrong version of Jackson got  installed - Jackson is a Java library that serializes/maps java objects to JSON and vice versa. Looking at the databricks documentation the version of the python library needs to match the cluster version:

```bash
pip install -U databricks-connect==7.1.*  # or X.Y.* to match your cluster version.
```
What is version did you install and what is the cluster version?
