### ISSUE TITLE
R Studio von Azure

### ISSUE THREAD

**Issue by dmangonakis** [Azure/DataScienceVM#37]
Hi there!

What is the best way of programmatically spinning up an R Studio environment on demand with specific dependencies, e.g. R version, CPU, packages, ... ?

Azure ML CI is a managed VM. Thus, you can't choose the R version you want. One may fire up another CI within R Studio for using a different R environments but that seems to decrease rapid experimentation.

Is DSVM as an unmanaged VM the way to go here? One may create DSVM environments via Azure CLI by using ARM (templates). Perhaps there is something that allows to specify the R version? 

AzureVM provides the vm_config function which allows to specify the image to deploy.

Any other ideas?

Thank you!

**Comment by samuel100** [comment]
@dmangonakis on the Ubuntu DSVM image docker is installed. Have you considered using rocker:

https://www.rocker-project.org/
