### ISSUE TITLE
Linux DSVM images not using PTP for timesync

### ISSUE THREAD

**Issue by mabicca** [Azure/DataScienceVM#48]
Hi everyone,

It seems that the DSVM images running Linux are not following the recommendations for timesync in Azure, described here:
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

The issue can be corrected by:

```
$ sudo apt install chrony
$ sudo mv /etc/chrony/chrony.conf /etc/chrony.conf.old
$ echo "keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
maxupdateskew 100.0
rtcsync
makestep 1.0 -1
local stratum 2
refclock PHC /dev/ptp_hyperv poll 3 dpoll -2 offset 0" > /etc/chrony/chrony.conf

$ sudo systemctl restart chronyd.service
$ sudo systemctl disable --now systemd-timesyncd
$ sudo systemctl enable chrony
```

We can then check it with:

```
$ sudo chronyc sources
```

Is there a way we can fix this in the current images so they come up correctly?

We are also updating the main reference about timesync on Azure with a few other remarks.

**Comment by jeff-shepherd** [comment]
@mabicca Are you referring to the Ubuntu 18.04 DSVM?
The current Ubuntu DSVM is 20.04.  I see chronyd is running by default on that image.

**Comment by mabicca** [comment]
Hi Jeff, thanks for the update. I believe for 20.04 we just need to add these lines to the chrony.conf:

''''
makestep 1.0 -1
local stratum 2
''''

Do we know if it's possible to update the older images as well?

**Comment by jeff-shepherd** [comment]
@mabicca Thanks
The Ubuntu 20.04 DSVM uses exactly the same chrony configuration as the regular Ubuntu 20.04 VM.
I think we should keep it that way. 

Why do you want "makestep 1.0 -1" and "local stratum 2" ?

We are not planning to update the Ubuntu 18.04 DSVM unless there is a critical issue.
Ubuntu 18.04 ends standard support in April 2023.

**Comment by mabicca** [comment]
@jeff-shepherd all Linux images on Azure should follow the recommended steps described on our link, in cases that we deviate from that configuration we have seen issues. 

It is all explained in the documentation here: https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

With all of that in place, we guarantee reliable timesync behavior on Azure for Linux based VMs.

**Comment by mabicca** [comment]
Hi @jeff-shepherd I believe there's not going to be a change for this? We should make sure our images are following our recommendations, we've seen a few issues and would like to avoid that. The images from Canonical should match our recommendations too.
